name: camera_recorder_cloud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_xlider: ^3.5.0
  gallery_saver: ^2.3.2
  image: ^4.1.7
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  syncfusion_flutter_sliders: ^25.1.35
  video_player: ^2.8.3
  video_compress: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - sfx/
  uses-material-design: true
